version: '3'
networks:
    api_server_default:
        external: true
services:
    temedica:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            ENV_NAME: dev
        ports:
            - 7001:7001
