version: '3.8'

services:
  nginx:
    build:
      context: ../..
      dockerfile: .docker/Cache.Dockerfile
    restart: unless-stopped
    depends_on:
      - server
    links:
      - server
    networks:
      - crewmeister
      - web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.imdemo.rule=Host(`demo.im.dunklestoast.de`)'
      - 'traefik.http.routers.imdemo.tls=true'
      - 'traefik.http.routers.imdemo.tls.certresolver=lets-encrypt'
      - 'traefik.http.services.imdemo.loadbalancer.server.port=80'
      - 'traefik.http.middlewares.imdemo.compress=true'
  server:
    build:
      context: ../..
      dockerfile: .docker/Server.Dockerfile
    restart: unless-stopped
    networks:
      - crewmeister
    depends_on:
      - redis
    environment:
      SERVER_PORT: 1337
      SERVER_HOST: 0.0.0.0
      LOG_LEVEL: info
      NODE_ENV: production
  storybook:
    restart: unless-stopped
    build:
      context: ../..
      dockerfile: .docker/Storybook.Dockerfile
    networks:
      - web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.imsb.rule=Host(`sb.im.dunklestoast.de`)'
      - 'traefik.http.routers.imsb.tls=true'
      - 'traefik.http.routers.imsb.tls.certresolver=lets-encrypt'
      - 'traefik.http.services.imsb.loadbalancer.server.port=80'
      - 'traefik.http.middlewares.imsb.compress=true'

networks:
  crewmeister:
  web:
    external: true
